name: CI

on:
  push:
    paths:
      - "**.py"
      - "**.kv"
  pull_request:
    paths:
      - "**.py"
      - "**.kv"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run Ruff Lint
        run: uvx ruff check --output-format=github .

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check formatting
        run: uvx ruff format --check .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Run tests
        env:
          PYTHONPATH: .
        run: uv run --env-file .env.development --no-project --with pytest pytest tests/
